### ISSUE TITLE
Usage with conformance test

### ISSUE THREAD

**Issue by gwawiork** [microsoft/OpenCLOn12#13]
Hi
I am trying to use this layer with https://github.com/KhronosGroup/OpenCL-CTS
I am working on one of the latest Windows 10 version on Intel KBL platform (Intel(R) HD Graphics 630)

I am not sure which steps should be done in order. 
What I did I downloaded Microsoft.D3DMappingLayers_1.2011.2.0_x64__8wekyb3d8bbwe.Appx (Microsoft store do not allowed me install this) and manually installed this on my Windows. Next I uninstalled Intel Graphics driver
I took my conformance binaries and run on this platform.
I see that tests runs and reports such device/platform:
`Compute Device Name = Microsoft Basic Render Driver, Compute Device Vendor = Microsoft, Compute Device Version = OpenCL 1.2 D3D12 Implementation, CL C Version = OpenCL C 1.2`
Is there any configuration that I will able to run application and see Compute Device Name  = Intel(R) HD Graphics 630 ?
Should the conformance tests be rebuild with OpenCLOn12 ?
For any tips and clarification, thank you very much.

**Comment by jenatali** [comment]
You can set environment variables for the conformance tests to change which platform and device they use. Set `CL_PLATFORM_INDEX=1` to force the tests to skip Intel's ICD-provided platform and use the second one, which should be CLOn12.

You can also set `CL_DEVICE_INDEX` to change which D3D device is used by the test. Any hardware devices should be first, so leaving it at 0 should choose the Intel GPU.

**Comment by gwawiork** [comment]
Thank you!
