### ISSUE TITLE
OpenCL is yet again incompatible with darktable 4.00

### ISSUE THREAD

**Issue by Myron-S** [microsoft/OpenCLOn12#39]
If I uninstall the compatibility pack then darktable 4.00 works correctly.

**Comment by jenatali** [comment]
I'm able to launch Darktable 4.00 with the pack installed. Is there more that's needed to reproduce a crash here?

**Comment by jenatali** [comment]
I'm going to go ahead and close this until I get more information since I was unable to reproduce. Please re-open if this is still hitting and you can give me more detailed reproduction steps.
