### ISSUE TITLE
Newer version of OpenCL like 3.0

### ISSUE THREAD

**Issue by VOM7HC** [microsoft/OpenCLOn12#63]
Currently this is support OpenCL 1.2, any plan for newer OpenCL version?

**Comment by jenatali** [comment]
Looks like the readme is stale. 3.0 has been supported since https://github.com/microsoft/OpenCLOn12/commit/a0887ededf3a6f9522109ec2c7ef0ea4426a2571.

**Comment by VOM7HC** [comment]
Great, thank @jenatali
